### ISSUE TITLE
重复了五次

### ISSUE THREAD

**Issue by q51005522555225** [11273/mooc-work-answer#106]
![1695031008410](https://github.com/11273/mooc-work-answer/assets/75592725/52ef0909-6914-4a62-88a8-2b87a5252732)
课程链接https://course.icve.com.cn/learnspace/learn/learn/templateeight/index.action?params.courseId=03b892db43a64593ae2ddf6286343ca5___&params.templateType=8&params.templateStyleType=0&params.template=templateeight&params.classId=&params.previewItemId=&params.tplRoot=learn

**Comment by q51005522555225** [comment]
https://mooc.icve.com.cn/cms/courseDetails/index.htm?cid=gclwhz037sd449

**Comment by q51005522555225** [comment]
[2023-09-18 17:56:26,897][16276][StartWork.py][line: 127][ERROR] :: Expecting value: line 2 column 1 (char 2)
Traceback (most recent call last):
  File "requests\models.py", line 971, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "StartWork.py", line 124, in <module>
  File "NewMoocMain\init_mooc.py", line 408, in run
  File "<string>", line 1, in <module>
  File "NewMoocMain\init_mooc.py", line 341, in openLearnResItem
  File "NewMoocMain\init_mooc.py", line 236, in course_topic_action
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

**Comment by 11273** [comment]
重新运行不会出现输入alicfw的提示吗

**Comment by q51005522555225** [comment]
输入也这样



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月24日 18:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [11273/mooc-work-answer] 重复了五次 (Issue #106) |

重新运行不会出现输入alicfw的提示吗
