### ISSUE TITLE
在存在多门课程时会出现异常结束的问题

### ISSUE THREAD

**Issue by bujinimeiyandongren** [11273/mooc-work-answer#118]
这是属于视频请求异常的问题吗？请求大佬解答
'data'
Traceback (most recent call last):
  File "StartWork.py", line 124, in <module>
  File "NewMoocMain\init_mooc.py", line 426, in run
  File "<string>", line 1, in <module>
  File "NewMoocMain\init_mooc.py", line 348, in openLearnResItem
KeyError: 'data'

**Comment by 11273** [comment]
和音频有关，具体课程是哪一门呢

**Comment by bujinimeiyandongren** [comment]
> 和音频有关，具体课程是哪一门呢

基站系统工程这门

**Comment by 11273** [comment]
试试最新版的 [v2.1.5](https://github.com/11273/mooc-work-answer/releases/tag/v2.1.5)
