### ISSUE TITLE
一到音频就报错怎么办

### ISSUE THREAD

**Issue by Osasn** [11273/mooc-work-answer#122]
'data'
Traceback (most recent call last):
  File "StartWork.py", line 124, in <module>
  File "NewMoocMain\init_mooc.py", line 415, in run
  File "<string>", line 1, in <module>
  File "NewMoocMain\init_mooc.py", line 348, in openLearnResItem
KeyError: 'data'

**Comment by 11273** [comment]
重新运行也这样吗

**Comment by Osasn** [comment]
> 重新运行也这样吗

对

**Comment by 11273** [comment]
哪一门课程，我看看我的会不会

**Comment by 11273** [comment]
试试最新版的 [v2.1.5](https://github.com/11273/mooc-work-answer/releases/tag/v2.1.5)
