### ISSUE TITLE
exe文件运行报错

### ISSUE THREAD

**Issue by 3078455271** [11273/mooc-work-answer#128]
HTTPSConnectionPool(host='sso.icve.com.cn', port=443): Max retries exceeded with url: /prod-api/data/userLoginV2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 667, in urlopen
  File "urllib3\connectionpool.py", line 932, in _prepare_proxy
  File "urllib3\connection.py", line 362, in connect
  File "urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 726, in urlopen
  File "urllib3\util\retry.py", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sso.icve.com.cn', port=443): Max retries exceeded with url: /prod-api/data/userLoginV2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "StartWork.py", line 129, in <module>
  File "NewMoocMain\init_mooc.py", line 415, in run
  File "NewMoocMain\init_mooc.py", line 47, in auth
  File "requests\sessions.py", line 578, in post
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='sso.icve.com.cn', port=443): Max retries exceeded with url: /prod-api/data/userLoginV2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
程序结束，如遇错误请重新运行，多次重复错误请提交Github...
![屏幕截图 2023-12-12 160357](https://github.com/11273/mooc-work-answer/assets/120673965/d977d991-be49-40a4-9cc2-3850eb407013)

**Comment by 11273** [comment]
是不是开了代理或者抓包呢
