### ISSUE TITLE
刷课的时候出现的问题

### ISSUE THREAD

**Issue by 3078455271** [11273/mooc-work-answer#132]
![Uploading 屏幕截图 2023-12-19 190454.png…]()

**Comment by 3078455271** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\mooc-work-answer-main\mooc-work-answer-main\NewMoocMain\init_mooc.py", line 368, in openLearnResItem
    aes = get_aes(session, course_id, item_id, audio_time, audio=True, start_time=start_time, end_time=end_time)
  File "C:\Users\Administrator\Downloads\mooc-work-answer-main\mooc-work-answer-main\NewMoocMain\init_mooc.py", line 304, in get_aes
    learning_time_save_learning_time(session, course_id, t)
  File "C:\Users\Administrator\Downloads\mooc-work-answer-main\mooc-work-answer-main\NewMoocMain\init_mooc.py", line 202, in learning_time_save_learning_time
    return post.json()
  File "D:\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by 11273** [comment]
哪门课程呢

**Comment by 11273** [comment]
重新运行试试

**Comment by 3078455271** [comment]
还是那样





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月19日(星期二) 晚上9:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [11273/mooc-work-answer] 刷课的时候出现的问题 (Issue #132)





 
重新运行试试

**Comment by RichY0608** [comment]
都差不多 是不是官网更新啥的

**Comment by 11273** [comment]
官网有更新反爬，待处理

**Comment by RichY0608** [comment]
> 官网有更新反爬，待处理

应该修复了吧

**Comment by 11273** [comment]
https://github.com/11273/mooc-work-answer/releases/tag/v2.1.8
已更新最新版
