### ISSUE TITLE
一个bug，会导致程序异常关闭

### ISSUE THREAD

**Issue by blg0515** [11273/mooc-work-answer#17]
![image](https://user-images.githubusercontent.com/52337543/165742986-d6e5b65e-b549-4506-a96e-692f97c56030.png)

**Comment by blg0515** [comment]
发生异常: KeyError
'uniqueId'
  File "E:\mooc-work-answer\MoocMain\workMain.py", line 303, in run_get_answer
    work_exam_save_res = workExamSave(cookies, work_exam_preview['uniqueId'], work_exam['Id'], work_exam_type)
  File "E:\mooc-work-answer\MoocMain\workMain.py", line 234, in run_start_work
    work_exam_answer_map = run_get_answer(ck2, work_exam_type, course_open_id, exam_item['Id'])
  File "E:\mooc-work-answer\StartWork.py", line 117, in <module>
    is_work_score)

**Comment by blg0515** [comment]
![image](https://user-images.githubusercontent.com/52337543/165743290-39395266-dd19-451c-bcda-01c59211d47f.png)

**Comment by blg0515** [comment]
【大号】 跳过课程       当前课程        【毛泽东思想和中国特色社会主义理论体系概论】
【大号】 开始答题       当前课程        【大学生职业生涯规划】
        1. 当前{作业}:【模块一单元作业】
Traceback (most recent call last):
  File "e:/mooc-work-answer/StartWork.py", line 117, in <module>
    is_work_score)
  File "e:\mooc-work-answer\MoocMain\workMain.py", line 234, in run_start_work
    work_exam_answer_map = run_get_answer(ck2, work_exam_type, course_open_id, exam_item['Id'])
  File "e:\mooc-work-answer\MoocMain\workMain.py", line 303, in run_get_answer
    work_exam_save_res = workExamSave(cookies, work_exam_preview['uniqueId'], work_exam['Id'], work_exam_type)
KeyError: 'uniqueId'

**Comment by 11273** [comment]
小号登录官网，把大号课程手动添加进去
