### ISSUE TITLE
新版遇到作业就报错

### ISSUE THREAD

**Issue by qfcxhh** [11273/mooc-work-answer#67]
![image](https://user-images.githubusercontent.com/74072720/218385991-460eb8f6-0ced-44c5-85c3-030e7da73c08.png)
Traceback (most recent call last):
  File "C:\Users\QFOWN\Desktop\mooc-work-answer-main\NewMoocMain\init_mooc.py", line 307, in <module>
    eval(get_xpath_text(s_point[k], "./@onclick").replace(";", ""))
  File "<string>", line 1, in <module>
  File "C:\Users\QFOWN\Desktop\mooc-work-answer-main\NewMoocMain\init_mooc.py", line 250, in openLearnResItem
    aes = get_aes(course_id, item_id, data_video_time)
  File "C:\Users\QFOWN\Desktop\mooc-work-answer-main\NewMoocMain\init_mooc.py", line 212, in get_aes
    t = time_to_seconds(video_total_time) + 0.0
  File "C:\Users\QFOWN\Desktop\mooc-work-answer-main\NewMoocMain\init_mooc.py", line 161, in time_to_seconds
    b = f.split(":")
AttributeError: 'NoneType' object has no attribute 'split'
错误是这个

**Comment by 11273** [comment]
已更新代码
