### ISSUE TITLE
新版使用

### ISSUE THREAD

**Issue by iwbiu** [11273/mooc-work-answer#80]
### 已经填好了了账号密码
> C:\Users\hw_13\Desktop\mooc-work-answer-main\NewMoocMain>python init_mooc.py
Traceback (most recent call last):
  File "init_mooc.py", line 16, in <module>
    from MoocMain.log import Logger
ModuleNotFoundError: No module named 'MoocMain'

这是报错，网页上登陆不了旧版mooc，只能登录新版
---
python版本 3.8.0

**Comment by 11273** [comment]
有pycharm吗，在pycharm运行

**Comment by iwbiu** [comment]
提示
> C:\Code\Python\python-3.11.0\python.exe C:\Users\hw_13\Desktop\mooc-work-answer-main\NewMoocMain\init_mooc.py 
Traceback (most recent call last):
  File "C:\Users\hw_13\Desktop\mooc-work-answer-main\NewMoocMain\init_mooc.py", line 14, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

**Comment by 11273** [comment]
```shell 
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
```

**Comment by iwbiu** [comment]
> 模拟滑块验证码中，请耐心等待...
成功。
{"code":200,"msg":"ok","data":"126f87ea-1a35-413a-935c-2870ba352122","sign":null}
{'loginId': 'B19516650809', 'data': [['园林植物景观设计', '第八期开课', '2023-02-10', '2023-05-27', '164', 'http://spoc.icve.com.cn/incoming/sites/zhzj/data/uploads/xjaaaber07bfhfbt3xxwag/pic/20230201031110_cut.jpeg', 'a297914fb0214d1cb3ecbf8d9ac70a5c', '', '上海城建职业学院', '', '60', '85', '', '2', '0', '朱红霞', 'c36d595b8d240f0eaad72636e74559ca', '', '', '']], 'totalPage': '1', 'errorCode': '200', 'newSiteCode': 'zhzj', 'totalCount': '1', 'errorMsg': ''}
【园林植物景观设计】{已学习时长: 待获取}- 第八期开课 2023-02-10 2023-05-27
Traceback (most recent call last):
  File "C:\Users\hw_13\Desktop\11\NewMoocMain\init_mooc.py", line 288, in <module>
    html_page_course = courseware_index(session, course_id)
  File "C:\Users\hw_13\Desktop\11\NewMoocMain\init_mooc.py", line 77, in courseware_index
    raise Exception("出现此提示，请网页退出账号并等待半小时或一小时后再执行!")
Exception: 出现此提示，请网页退出账号并等待半小时或一小时后再执行!

**Comment by 11273** [comment]
临时风控了，要等一会

**Comment by iwbiu** [comment]
大概多久呢

**Comment by 11273** [comment]
等十几分钟再试试

**Comment by iwbiu** [comment]
运行第一次的时候，只完成了几个视频，然后就报错了
第二次运行的时候
> 模拟滑块验证码中，请耐心等待...
成功。
{"code":200,"msg":"ok","data":"7fa3fe45-d949-41e6-b23d-20d047fbbc1a","sign":null}
{'loginId': 'B19516650809', 'data': [['园林植物景观设计', '第八期开课', '2023-02-10', '2023-05-27', '164', 'http://spoc.icve.com.cn/incoming/sites/zhzj/data/uploads/xjaaaber07bfhfbt3xxwag/pic/20230201031110_cut.jpeg', 'a297914fb0214d1cb3ecbf8d9ac70a5c', '', '上海城建职业学院', '', '60', '85', '', '2', '0', '朱红霞', 'c36d595b8d240f0eaad72636e74559ca', '', '', '']], 'totalPage': '1', 'errorCode': '200', 'newSiteCode': 'zhzj', 'totalCount': '1', 'errorMsg': ''}
【园林植物景观设计】{已学习时长: 待获取}- 第八期开课 2023-02-10 2023-05-27
Traceback (most recent call last):
  File "C:\Users\hw_13\Desktop\11\NewMoocMain\init_mooc.py", line 288, in <module>
    html_page_course = courseware_index(session, course_id)
  File "C:\Users\hw_13\Desktop\11\NewMoocMain\init_mooc.py", line 77, in courseware_index
    raise Exception("出现此提示，请网页退出账号并等待半小时或一小时后再执行!")
Exception: 出现此提示，请网页退出账号并等待半小时或一小时后再执行!

**Comment by iwbiu** [comment]
## 到这里就结束了
> 任务2.5植物景观的文化设计
			 视频：古典园林植物文化内涵和配置方法
				 ~~~~>执行结果: 保存成功
			 视频：传统植物文化的继承和发展
				 ~~~~>执行结果: 保存成功
			 主题讨论：古典园林植物文化的应用
Traceback (most recent call last):
  File "C:\Users\hw_13\Desktop\11\NewMoocMain\init_mooc.py", line 315, in <module>
    eval(get_xpath_text(s_point[k], "./@onclick").replace(";", ""))
  File "<string>", line 1, in <module>
  File "C:\Users\hw_13\Desktop\11\NewMoocMain\init_mooc.py", line 258, in openLearnResItem
    course_item_learn_record = learning_time_save_course_item_learn_record(session, course_id, item_id)
  File "C:\Users\hw_13\Desktop\11\NewMoocMain\init_mooc.py", line 111, in learning_time_save_course_item_learn_record
    return post.json()
  File "C:\Users\hw_13\Desktop\11\venv\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Code\Python\python-3.8.0\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Code\Python\python-3.8.0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Code\Python\python-3.8.0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 
## 但是我远不止2.5个章节

**Comment by 11273** [comment]
应该还是被风控了，晚点才能解决
