### ISSUE TITLE
这个情况怎么搞

### ISSUE THREAD

**Issue by q51005522555225** [11273/mooc-work-answer#94]
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "StartWork.py", line 119, in <module>
  File "NewMoocMain\init_mooc.py", line 286, in run
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by 11273** [comment]
重新运行

**Comment by q51005522555225** [comment]
运行一会就这样了。刷了四个项目

Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "StartWork.py", line 119, in <module>
  File "NewMoocMain\init_mooc.py", line 323, in run
  File "<string>", line 1, in <module>
  File "NewMoocMain\init_mooc.py", line 269, in openLearnResItem
  File "NewMoocMain\init_mooc.py", line 136, in learning_time_save_video_learn_time_long_record
  File "requests\models.py", line 898, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
程序结束...

**Comment by 11273** [comment]
还是要重新运行
